
# main config file for experiment1
# experiment1 name
experiment_name: experiment1
# config template and config of variations for running batch experiments
defaults:
  - conf_tmpl: experiment1
  - conf_vars/experiment1:
      - var1
      - var2
  - _self_
